version: "3.9"
services:
  scrapydweb:
    build:
      context: ./scrapydweb
    depends_on:
      - scrapyd
    ports:
      - "5000:5000"
    volumes:
      - ./scrapydweb_settings_v10.py:/app/scrapydweb_settings_v10.py
    # restart: always
  scrapyd:
    build:
      context: ./scrapyd
    ports:
      - "6800:6800"
    volumes:
      - ./scrapyd.conf:/root/.scrapyd.conf
    # restart: always
